version: '3.4'
services:
  mongodb:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb
volumes:
  mongodb:
    name: mongodb
